import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { NextUiProvider } from "./_providers/ui/NextUiProvider";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <NextUiProvider>
          <main className="flex min-h-screen flex-col items-center justify-start bg-slate-100">
            {children}
          </main>
        </NextUiProvider>
      </body>
    </html>
  );
}
